apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-backend-store

  target:
    name: app-secrets
    creationPolicy: Owner

  data:
  - secretKey: app-scroll
    remoteRef: 
      key: TheScroll
