apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-backend-store
spec:
  provider:
    azurekv:
      tenantId: <tenant_id> 
      vaultUrl: "https://kv-test-sbx-eu-01.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
